// <auto-generated />
using System;
using GraphDataStructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphDataStructure.Migrations
{
    [DbContext(typeof(GraphDSContext))]
    [Migration("20190817195301_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("GraphDataStructure.Models.Node", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("GraphDataStructure.Models.Relation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("NodeAId");

                    b.Property<long?>("NodeBId");

                    b.HasKey("Id");

                    b.HasIndex("NodeAId");

                    b.HasIndex("NodeBId");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("GraphDataStructure.Models.Relation", b =>
                {
                    b.HasOne("GraphDataStructure.Models.Node", "NodeA")
                        .WithMany()
                        .HasForeignKey("NodeAId");

                    b.HasOne("GraphDataStructure.Models.Node", "NodeB")
                        .WithMany()
                        .HasForeignKey("NodeBId");
                });
#pragma warning restore 612, 618
        }
    }
}
